name: Build Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions: read-all

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
  build:
    name: Build Python Package
    runs-on: ubuntu-latest
    needs: [ci]
    env:
      BACKEND_DIR: ./backend
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: ./.github/actions/pnpm-node-install
        name: Install Node, pnpm and dependencies
        with:
          pnpm-install-args: --no-frozen-lockfile
      - uses: ./.github/actions/poetry-python-install
        name: Install Python, poetry and Python dependencies
        with:
          poetry-working-directory: ${{ env.BACKEND_DIR }}
      - name: Build Python distribution
        run: poetry self add poetry-plugin-ignore-build-script && poetry build --ignore-build-script
        working-directory: ${{ env.BACKEND_DIR }}
      - name: Upload Python package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: ${{ env.BACKEND_DIR }}/dist/*
          retention-days: 7
